import About from '@/components/About'
import Main from '@/components/Main'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'
import { projectRoutes } from '@/components/projectRoutes'
import Head from 'next/head'

export default function Home({projects}) {
  return (
    <>
      <Head>
        <title>Harshit | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      
    <Main />
    <About />
    <Skills />
    <Projects projects={projects} />
    </>
  )
}


export const  getStaticProps = () => {

  const projects = projectRoutes;

  return {
    props: {
      projects
    }
  };
}

