import About from '@/components/About'
import Main from '@/components/Main'
import Navbar from '@/components/Navbar'
import ProjectList from '@/components/ProjectList'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'
import { projectRoutes } from '@/projectRoutes'
import Head from 'next/head'
import Image from 'next/image'



export default function Home({project}) {
  return (
    <>
      <Head>
        <title>Harshit | Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      
    {/* <Main /> */}
    <ProjectList projects={project} />
    <About />
    <Skills />
    <Projects />
    </>
  )
}


export const  getStaticProps = () => {

  const project = projectRoutes;

  return {
    props: {
      project 
    }
  };
}

